//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desk.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IFinancialOps", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IFinancialOps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialOps/NewOrder", ReplyAction="http://tempuri.org/IFinancialOps/NewOrderResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool NewOrder(int client, string email, int op, int type, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialOps/GetStatus", ReplyAction="http://tempuri.org/IFinancialOps/GetStatusResponse")]
        int GetStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialOps/ChangeOrder", ReplyAction="http://tempuri.org/IFinancialOps/ChangeOrderResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool ChangeOrder(int id, double cotation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialOps/GetWaitingRequests", ReplyAction="http://tempuri.org/IFinancialOps/GetWaitingRequestsResponse")]
        int[] GetWaitingRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialOps/GetRequestsByClient", ReplyAction="http://tempuri.org/IFinancialOps/GetRequestsByClientResponse")]
        string[][] GetRequestsByClient(int client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinancialOpsChannel : Desk.Server.IFinancialOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialOpsClient : System.ServiceModel.ClientBase<Desk.Server.IFinancialOps>, Desk.Server.IFinancialOps {
        
        public FinancialOpsClient() {
        }
        
        public FinancialOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool NewOrder(int client, string email, int op, int type, int quantity) {
            return base.Channel.NewOrder(client, email, op, type, quantity);
        }
        
        public int GetStatus(int id) {
            return base.Channel.GetStatus(id);
        }
        
        public bool ChangeOrder(int id, double cotation) {
            return base.Channel.ChangeOrder(id, cotation);
        }
        
        public int[] GetWaitingRequests() {
            return base.Channel.GetWaitingRequests();
        }
        
        public string[][] GetRequestsByClient(int client) {
            return base.Channel.GetRequestsByClient(client);
        }
    }
}
